---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role-list
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - mco.in-cloud.io
  resources:
  - machineconfigpools
  - renderedmachineconfigs
  - machineconfigs
  verbs:
  - get
  - list
  - watch
