apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: system
  labels:
    app.kubernetes.io/name: mco-agent
    app.kubernetes.io/component: agent
    app.kubernetes.io/managed-by: kustomize
